export const PERM_SETS = {
  homeLocalPortal: ["ops.orders.create", "orders.create", "ops.orders.list", "orders.view"],
  homeDepositoPortal: ["ops.stock_movements.create", "stock.register", "stock.adjust", "stock.transfer"],
  homePlantaPortal: ["ops.production.lots.view", "production.view", "ops.shipments.create", "shipments.create"],

  produccion: ["ops.production.lots.list", "ops.production.lots.read", "production.view"],
  stock: ["ops.stock_levels.list", "ops.stock_movements.list", "stock.view"],
  stockMovimientos: ["ops.stock_movements.list", "ops.stock_movements.create", "stock.register"],
  stockInventarios: ["ops.inventory_counts.list", "ops.inventory_counts.create", "ops.inventory_counts.read"],
  mermas: ["ops.mermas.list", "ops.mermas.create"],
  pedidos: ["ops.orders.list", "orders.view"],
  envios: ["ops.shipments.list", "ops.shipments.create", "ops.shipments.read", "shipments.view", "shipments.create"],
  remitos: ["ops.remitos.list", "ops.remitos.read", "remitos.view"],
  compras: ["ops.purchases.receipts.list", "ops.purchases.receipts.create"],
  pedidosIngreso: ["ops.orders.create", "orders.create"],
  administracion: ["admin.users.list", "admin.rbac.roles.list", "admin.rbac.permissions.list"],
  auditoria: ["admin.audit.logs.read", "admin.audit.logs.meta"],
  reportes: ["report.stock.alerts.read", "report.stock.expirations.read", "report.stock.summary.read"],

  mobileProduccion: ["ops.production.lots.list", "ops.production.lots.read", "production.view"],
  mobilePedidos: ["ops.orders.list", "orders.view"],
  mobileEnvios: ["ops.remitos.list", "ops.remitos.read", "remitos.view", "remitos.create", "remitos.edit"],
};

export const ROUTE_PERMISSION_RULES: Record<string, string[]> = {
  "/": [],
  "/produccion": [...PERM_SETS.produccion],
  "/stock": [...PERM_SETS.stock],
  "/stock/movimientos": [...PERM_SETS.stockMovimientos],
  "/stock/inventarios": [...PERM_SETS.stockInventarios],
  "/mermas": [...PERM_SETS.mermas],
  "/pedidos": [...PERM_SETS.pedidos],
  "/envios": [...PERM_SETS.envios],
  "/envios/:shipmentId": [...PERM_SETS.envios],
  "/envios/:shipmentId/preparar": [...PERM_SETS.envios],
  "/remitos": [...PERM_SETS.remitos],
  "/compras": [...PERM_SETS.compras],
  "/pedidos/ingreso": [...PERM_SETS.pedidosIngreso],
  "/administracion": [...PERM_SETS.administracion],
  "/auditoria": [...PERM_SETS.auditoria],
  "/reportes": [...PERM_SETS.reportes],
  "/mobile/produccion": [...PERM_SETS.mobileProduccion],
  "/mobile/pedidos": [...PERM_SETS.mobilePedidos],
  "/mobile/envios": [...PERM_SETS.mobileEnvios],
  "/mobile/envios/:shipmentId/preparar": [...PERM_SETS.mobileEnvios],
};
