export const ROUTE_PERMISSION_RULES: Record<string, string[]> = {
  "/": [],
  "/produccion": ["ops.production.lots.list", "ops.production.lots.read"],
  "/stock": ["ops.stock_levels.list", "ops.stock_movements.list"],
  "/stock/movimientos": ["ops.stock_movements.list", "ops.stock_movements.create"],
  "/stock/inventarios": ["ops.inventory_counts.list", "ops.inventory_counts.create", "ops.inventory_counts.read"],
  "/mermas": ["ops.mermas.list", "ops.mermas.create"],
  "/pedidos": ["ops.orders.list", "ops.orders.create", "ops.orders.read"],
  "/envios": ["ops.shipments.list", "ops.shipments.create", "ops.shipments.read"],
  "/envios/:shipmentId": ["ops.shipments.list", "ops.shipments.create", "ops.shipments.read"],
  "/envios/:shipmentId/preparar": ["ops.shipments.list", "ops.shipments.create", "ops.shipments.read"],
  "/remitos": ["ops.remitos.list", "ops.remitos.read"],
  "/compras": ["ops.purchases.receipts.list", "ops.purchases.receipts.create"],
  "/pedidos/ingreso": ["ops.orders.create", "ops.lookups.order_entry_skus.list"],
  "/administracion": ["admin.users.list", "admin.rbac.roles.list", "admin.rbac.permissions.list"],
  "/auditoria": ["admin.audit.logs.read", "admin.audit.logs.meta"],
  "/reportes": ["report.stock.alerts.read", "report.stock.expirations.read", "report.stock.summary.read"],
  "/mobile/produccion": ["production.view"],
  "/mobile/pedidos": ["orders.view"],
  "/mobile/envios": ["remitos.view", "remitos.create", "remitos.edit"],
  "/mobile/envios/:shipmentId/preparar": ["remitos.view", "remitos.create", "remitos.edit"],
};
