export const ROUTE_PERMISSION_RULES: Record<string, string[]> = {
  "/": ["dashboard.view"],
  "/produccion": ["production.view"],
  "/stock": ["stock.view"],
  "/stock/movimientos": ["stock.view"],
  "/stock/inventarios": ["inventory.view"],
  "/mermas": ["mermas.view"],
  "/pedidos": ["orders.view"],
  "/envios": ["remitos.view", "remitos.create", "remitos.edit"],
  "/envios/:shipmentId": ["remitos.view", "remitos.create", "remitos.edit"],
  "/envios/:shipmentId/preparar": ["remitos.view", "remitos.create", "remitos.edit"],
  "/remitos": ["remitos.view"],
  "/compras": ["purchases.view"],
  "/pedidos/ingreso": ["orders.create"],
  "/administracion": ["roles.view"],
  "/auditoria": ["audit.view"],
  "/reportes": ["reports.view"],
  "/mobile/produccion": ["production.view"],
  "/mobile/pedidos": ["orders.view"],
  "/mobile/envios": ["remitos.view", "remitos.create", "remitos.edit"],
  "/mobile/envios/:shipmentId/preparar": ["remitos.view", "remitos.create", "remitos.edit"],
};
