from __future__ import annotations

ROUTE_PERMISSION_MAP: dict[tuple[str, str], str] = {
    ("GET", "/api/permissions"): "admin.rbac.permissions.list",
    ("GET", "/api/roles"): "admin.rbac.roles.list",
    ("GET", "/api/roles/{role_id}/permissions"): "admin.rbac.roles.permissions.read",
    ("PUT", "/api/roles/{role_id}/permissions"): "admin.rbac.roles.permissions.update",
    ("GET", "/api/users"): "admin.users.list",
    ("POST", "/api/users"): "admin.users.create",
    ("PUT", "/api/users/{user_id}"): "admin.users.update",
    ("DELETE", "/api/users/{user_id}"): "admin.users.delete",
    ("PATCH", "/api/users/{user_id}/pin"): "admin.users.update_pin",
    ("GET", "/api/audit/logs"): "admin.audit.logs.read",
    ("GET", "/api/audit/logs/meta"): "admin.audit.logs.meta",
    ("GET", "/api/audit/logs/export.xlsx"): "admin.audit.logs.export",
    ("GET", "/api/deposits"): "ops.lookups.deposits.list",
    ("POST", "/api/deposits"): "master.deposits.create",
    ("PUT", "/api/deposits/{deposit_id}"): "master.deposits.update",
    ("PATCH", "/api/deposits/{deposit_id}/status"): "master.deposits.update_status",
    ("DELETE", "/api/deposits/{deposit_id}"): "master.deposits.delete",
    ("GET", "/api/units"): "ops.lookups.units.list",
    ("GET", "/api/sku-types"): "master.sku_types.list",
    ("POST", "/api/sku-types"): "master.sku_types.create",
    ("PUT", "/api/sku-types/{sku_type_id}"): "master.sku_types.update",
    ("DELETE", "/api/sku-types/{sku_type_id}"): "master.sku_types.delete",
    ("GET", "/api/skus"): "ops.lookups.skus.list",
    ("POST", "/api/skus"): "master.skus.create",
    ("PUT", "/api/skus/{sku_id}"): "master.skus.update",
    ("PATCH", "/api/skus/{sku_id}/status"): "master.skus.update_status",
    ("DELETE", "/api/skus/{sku_id}"): "master.skus.delete",
    ("GET", "/api/skus/export.xlsx"): "report.master.skus.export",
    ("GET", "/api/orders"): "ops.orders.list",
    ("POST", "/api/orders"): "ops.orders.create",
    ("GET", "/api/orders/{order_id}"): "ops.orders.read",
    ("PUT", "/api/orders/{order_id}"): "ops.orders.update_draft",
    ("DELETE", "/api/orders/{order_id}"): "ops.orders.delete_draft",
    ("POST", "/api/orders/{order_id}/status"): "ops.orders.change_status",
    ("GET", "/api/orders/catalog"): "ops.lookups.order_entry_skus.list",
    ("GET", "/api/orders/stores"): "ops.lookups.order_stores.list",
    ("GET", "/api/shipments"): "ops.shipments.list",
    ("POST", "/api/shipments"): "ops.shipments.create",
    ("GET", "/api/shipments/{shipment_id}"): "ops.shipments.read",
    ("PUT", "/api/shipments/{shipment_id}"): "ops.shipments.update_draft",
    ("POST", "/api/shipments/{shipment_id}/add-orders"): "ops.shipments.add_orders",
    ("POST", "/api/shipments/{shipment_id}/items"): "ops.shipments.set_items",
    ("POST", "/api/shipments/{shipment_id}/prep-items"): "ops.shipments.prep_items",
    ("POST", "/api/shipments/{shipment_id}/confirm"): "ops.shipments.confirm",
    ("POST", "/api/shipments/{shipment_id}/dispatch"): "ops.shipments.dispatch",
    ("POST", "/api/shipments/{shipment_id}/cancel"): "ops.shipments.cancel",
    ("GET", "/api/shipments/{shipment_id}/pick-list.pdf"): "ops.shipments.pick_list.print",
    ("GET", "/api/remitos"): "ops.remitos.list",
    ("GET", "/api/remitos/{remito_id}"): "ops.remitos.read",
    ("GET", "/api/remitos/{remito_id}/pdf"): "ops.remitos.print",
    ("POST", "/api/remitos/from-order/{order_id}"): "ops.remitos.create_from_order",
    ("POST", "/api/remitos/{remito_id}/dispatch"): "ops.remitos.dispatch",
    ("POST", "/api/remitos/{remito_id}/receive"): "ops.remitos.receive",
    ("POST", "/api/remitos/{remito_id}/cancel"): "ops.remitos.cancel",
    ("GET", "/api/inventory-counts"): "ops.inventory_counts.list",
    ("POST", "/api/inventory-counts"): "ops.inventory_counts.create",
    ("GET", "/api/inventory-counts/{count_id}"): "ops.inventory_counts.read",
    ("PUT", "/api/inventory-counts/{count_id}"): "ops.inventory_counts.update_draft",
    ("POST", "/api/inventory-counts/{count_id}/submit"): "ops.inventory_counts.submit",
    ("POST", "/api/inventory-counts/{count_id}/approve"): "ops.inventory_counts.approve",
    ("POST", "/api/inventory-counts/{count_id}/close"): "ops.inventory_counts.close",
    ("POST", "/api/inventory-counts/{count_id}/cancel"): "ops.inventory_counts.cancel",
    ("PATCH", "/api/lots/{source_type}/{source_id}"): "ops.inventory.lots.update_expiry",
    ("GET", "/api/mermas"): "ops.mermas.list",
    ("POST", "/api/mermas"): "ops.mermas.create",
    ("GET", "/api/mermas/{merma_id}"): "ops.mermas.read",
    ("GET", "/api/mermas/lots"): "ops.lookups.merma_lots.list",
    ("GET", "/api/mermas/types"): "ops.lookups.merma_types.list",
    ("GET", "/api/mermas/causes"): "ops.lookups.merma_causes.list",
    ("POST", "/api/mermas/types"): "master.mermas.types.create",
    ("PUT", "/api/mermas/types/{type_id}"): "master.mermas.types.update",
    ("DELETE", "/api/mermas/types/{type_id}"): "master.mermas.types.delete",
    ("POST", "/api/mermas/causes"): "master.mermas.causes.create",
    ("PUT", "/api/mermas/causes/{cause_id}"): "master.mermas.causes.update",
    ("DELETE", "/api/mermas/causes/{cause_id}"): "master.mermas.causes.delete",
    ("GET", "/api/overheads/daily"): "ops.production.overheads_daily.list",
    ("POST", "/api/overheads/daily"): "ops.production.overheads_daily.create",
    ("GET", "/api/overheads/daily/{overhead_id}"): "ops.production.overheads_daily.read",
    ("PATCH", "/api/overheads/daily/{overhead_id}"): "ops.production.overheads_daily.update",
    ("GET", "/api/overheads/daily/{overhead_id}/allocations"): "ops.production.overheads_daily.allocations.read",
    ("GET", "/api/overheads/daily/{overhead_id}/items"): "ops.production.overheads_daily.items.list",
    ("POST", "/api/overheads/daily/{overhead_id}/items"): "ops.production.overheads_daily.items.create",
    ("PATCH", "/api/overheads/daily/{overhead_id}/items/{item_id}"): "ops.production.overheads_daily.items.update",
    ("DELETE", "/api/overheads/daily/{overhead_id}/items/{item_id}"): "ops.production.overheads_daily.items.delete",
    ("GET", "/api/production/lots"): "ops.production.lots.list",
    ("GET", "/api/production/lots/{lot_id}"): "ops.production.lots.read",
    ("GET", "/api/production/piecework"): "ops.production.piecework.read_daily",
    ("GET", "/api/production-lines/piece-rates"): "ops.production.piece_rates.list",
    ("POST", "/api/production-lines/{production_line_id}/piece-rate"): "master.production_lines.piece_rates.set",
    ("GET", "/api/production-lines"): "ops.lookups.production_lines.list",
    ("POST", "/api/production-lines"): "master.production_lines.create",
    ("PUT", "/api/production-lines/{line_id}"): "master.production_lines.update",
    ("GET", "/api/purchases/receipts"): "ops.purchases.receipts.list",
    ("POST", "/api/purchases/receipts"): "ops.purchases.receipts.create",
    ("GET", "/api/purchases/receipts/{receipt_id}"): "ops.purchases.receipts.read",
    ("GET", "/api/suppliers"): "ops.lookups.suppliers.list",
    ("POST", "/api/suppliers"): "master.suppliers.create",
    ("PUT", "/api/suppliers/{supplier_id}"): "master.suppliers.update",
    ("GET", "/api/recipes"): "master.recipes.list",
    ("POST", "/api/recipes"): "master.recipes.create",
    ("PUT", "/api/recipes/{recipe_id}"): "master.recipes.update",
    ("PATCH", "/api/recipes/{recipe_id}/status"): "master.recipes.update_status",
    ("DELETE", "/api/recipes/{recipe_id}"): "master.recipes.delete",
    ("GET", "/api/stock-levels"): "ops.stock_levels.list",
    ("GET", "/api/stock/movements"): "ops.stock_movements.list",
    ("POST", "/api/stock/movements"): "ops.stock_movements.create",
    ("GET", "/api/stock/movement-types"): "ops.lookups.stock_movement_types.list",
    ("POST", "/api/stock/movement-types"): "master.stock_movement_types.create",
    ("PUT", "/api/stock/movement-types/{movement_type_id}"): "master.stock_movement_types.update",
    ("DELETE", "/api/stock/movement-types/{movement_type_id}"): "master.stock_movement_types.delete",
    ("GET", "/api/reports/stock-alerts"): "report.stock.alerts.read",
    ("GET", "/api/reports/stock-expirations"): "report.stock.expirations.read",
    ("GET", "/api/reports/stock-summary"): "report.stock.summary.read",
    ("PATCH", "/api/stock/alerts/thresholds/{sku_id}"): "report.stock.alerts.set_threshold",
}

PUBLIC_WHITELIST = {
    ("GET", "/api/health"),
    ("POST", "/api/auth/login"),
    ("POST", "/api/auth/login-pin"),
}

AUTH_ONLY = {
    ("GET", "/api/auth/me"),
    ("POST", "/api/auth/verify-pin"),
}

DOC_PATHS = {"/docs", "/redoc", "/openapi.json", "/docs/oauth2-redirect"}
